config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'

  resources :products
  root 'pages#home'
  
  get 'about' => 'pages#about', as: :about

  get 'contact' => 'pages#contact', as: :contact

  get 'services' => 'pages#service', as: :service

  get 'smartphone' => 'store#index', as: 'store'
  

end

app/views/shared/_navbar.html.erb
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Express Repair", root_path, :class => 'navbar-brand' %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <%= link_to "home", root_path %>
                    </li>
                    
                    <li>
                        <%= link_to "about", about_path %>
                    </li>
					
					<li>
						<%= link_to "service", service_path %>
					</li>	
                    
                    <li>
                        <%= link_to "contact", contact_path %>
                    </li>
					<li>
						<%= link_to "smartphone", store_path %>
					</li>
					
            </div>
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>